/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Priyanshu
 */
public class Bhatt_MathMethodsFrame extends javax.swing.JFrame {

    /**
     * Creates new form Bhatt_MathMethodsFrame
     */
    public Bhatt_MathMethodsFrame() {
        initComponents();
    }

    // Variables
    
    int large1 = 0;
    int large2 = 0;
    int small1 = 0;
    int small2 = 0;
    int number = 0;
    int power = 0;
    int side1 = 0;
    int side2 = 0;
    int resultDown = 0;
    double roundDown = 0;
    int resultUp = 0;
    double roundUp = 0;
    int multiply1 = 0;
    int multiply2 = 0;
    int divide1 = 0;
    int divide2 = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLargest = new javax.swing.JLabel();
        lblSmallest = new javax.swing.JLabel();
        lblPowers = new javax.swing.JLabel();
        lblDown = new javax.swing.JLabel();
        lblUp = new javax.swing.JLabel();
        lblRoot = new javax.swing.JLabel();
        lblHypotenuse = new javax.swing.JLabel();
        lblRadians = new javax.swing.JLabel();
        buttonDown = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonLargest = new javax.swing.JButton();
        buttonSmallest = new javax.swing.JButton();
        buttonPowers = new javax.swing.JButton();
        buttonHypotenuse = new javax.swing.JButton();
        buttonUp = new javax.swing.JButton();
        txtLarge1 = new javax.swing.JTextField();
        txtLarge2 = new javax.swing.JTextField();
        txtSmallest1 = new javax.swing.JTextField();
        txtSmallest2 = new javax.swing.JTextField();
        txtMult1 = new javax.swing.JTextField();
        txtNumber = new javax.swing.JTextField();
        txtPower = new javax.swing.JTextField();
        txtSide1 = new javax.swing.JTextField();
        txtSide2 = new javax.swing.JTextField();
        txtDown = new javax.swing.JTextField();
        txtUp = new javax.swing.JTextField();
        txtDivide1 = new javax.swing.JTextField();
        outputLargest = new javax.swing.JTextField();
        outputSmallest = new javax.swing.JTextField();
        outputPower = new javax.swing.JTextField();
        outputHypotenuse = new javax.swing.JTextField();
        outputRDown = new javax.swing.JTextField();
        outputRUp = new javax.swing.JTextField();
        outputDivide = new javax.swing.JTextField();
        outputMultiply = new javax.swing.JTextField();
        txtDivide2 = new javax.swing.JTextField();
        txtMult2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText(" Math Methods");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Enter two numbers and click the button. The program will display the largest of the two numbers.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Enter two numbers. The program will divde the first number from the second number.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Enter two numbers and click the button. The program will display the smallest of the two numbers.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Enter two numbers and click the button. The program will display the first number to the power of the second.");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Enter the length of two sides of a right angle triangle. The program will display the hypotenuse of the two numbers.");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer. ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer. ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Enter two numbers. The program will multiply both the numbers.");

        buttonDown.setText("Rounded Down");
        buttonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownActionPerformed(evt);
            }
        });

        buttonMultiply.setText("Multiply");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonDivide.setText("Divide");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonLargest.setText("Largest");
        buttonLargest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLargestActionPerformed(evt);
            }
        });

        buttonSmallest.setText("Smallest");
        buttonSmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSmallestActionPerformed(evt);
            }
        });

        buttonPowers.setText("To The Power Of...");
        buttonPowers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowersActionPerformed(evt);
            }
        });

        buttonHypotenuse.setText("Hypotenuse");
        buttonHypotenuse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHypotenuseActionPerformed(evt);
            }
        });

        buttonUp.setText("Rounded Up");
        buttonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpActionPerformed(evt);
            }
        });

        txtDivide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDivide1ActionPerformed(evt);
            }
        });

        outputLargest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputLargestActionPerformed(evt);
            }
        });

        outputPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputPowerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSmallest1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSmallest2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSmallest)
                        .addGap(46, 46, 46)
                        .addComponent(lblSmallest)
                        .addGap(57, 57, 57)
                        .addComponent(outputSmallest, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtUp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblUp))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtDown, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDown)))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(outputRDown, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outputRUp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonPowers)
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPowers)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(outputPower, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSide1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSide2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonHypotenuse)
                                        .addGap(46, 46, 46)
                                        .addComponent(lblHypotenuse)
                                        .addGap(115, 115, 115))
                                    .addComponent(outputHypotenuse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLarge1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLarge2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonLargest)
                                .addGap(80, 80, 80)
                                .addComponent(lblLargest)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(outputLargest, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(outputMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txtDivide1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(lblRadians))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtDivide2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDivide)
                                .addGap(108, 108, 108)
                                .addComponent(outputDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonDown)
                                .addComponent(jLabel7)
                                .addComponent(buttonUp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtMult1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMult2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMultiply)
                        .addGap(46, 46, 46)
                        .addComponent(lblRoot)
                        .addGap(165, 165, 165))))
            .addGroup(layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargest)
                    .addComponent(buttonLargest)
                    .addComponent(txtLarge1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLarge2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputLargest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSmallest)
                    .addComponent(buttonSmallest)
                    .addComponent(txtSmallest1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSmallest2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputSmallest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPowers)
                    .addComponent(buttonPowers)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHypotenuse)
                    .addComponent(buttonHypotenuse)
                    .addComponent(txtSide1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSide2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputHypotenuse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDown)
                    .addComponent(lblDown)
                    .addComponent(txtDown, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputRDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUp)
                    .addComponent(buttonUp)
                    .addComponent(txtUp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputRUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRoot)
                            .addComponent(buttonMultiply)
                            .addComponent(txtMult1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMult2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(outputMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRadians)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(outputDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDivide1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtDivide2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(buttonDivide))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLargestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLargestActionPerformed
        // TODO add your handling code here:
    
       // Methods below, consisting of all commands for each sort of question
        
       largest ();
        
    }//GEN-LAST:event_buttonLargestActionPerformed

    private void buttonSmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSmallestActionPerformed
        // TODO add your handling code here:
    
       smallest (); 
        
    }//GEN-LAST:event_buttonSmallestActionPerformed

    private void buttonPowersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPowersActionPerformed
        // TODO add your handling code here:
    
       power ();     
    
    }//GEN-LAST:event_buttonPowersActionPerformed

    private void buttonHypotenuseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHypotenuseActionPerformed
        // TODO add your handling code here:
     
       hypotenuse ();
   
    }//GEN-LAST:event_buttonHypotenuseActionPerformed

    private void buttonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownActionPerformed
        // TODO add your handling code here:
    
       roundingD ();
        
    }//GEN-LAST:event_buttonDownActionPerformed

    private void buttonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpActionPerformed
        // TODO add your handling code here:

       roundingU ();
    
    }//GEN-LAST:event_buttonUpActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        // TODO add your handling code here:

       multiplying ();
        
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        // TODO add your handling code here:
        
      dividing ();
        
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void outputLargestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputLargestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputLargestActionPerformed

    private void outputPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputPowerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputPowerActionPerformed

    private void txtDivide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDivide1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDivide1ActionPerformed

    private int largest ()
    {    
        int largest = 0;
        
        // This gets the value from the user    
        
        large1 = Integer.parseInt(txtLarge1.getText()); 
        large2 = Integer.parseInt(txtLarge2.getText()); 

        // This does the math, converts to string and displays the answer

        double result = Math.max(large1, large2);
        int value = (int)result;
        outputLargest.setText(String.valueOf(value)) ;
        
        return largest;              
    }
    
    private int smallest ()
    {    
        int smallest = 0;
        
        // This gets the value from the user    
       
        small1 = Integer.parseInt(txtSmallest1.getText()); 
        small2 = Integer.parseInt(txtSmallest2.getText()); 

        // This does the math, converts to string and displays the answer

        double result = Math.min(small1, small2);
        int value = (int)result;
        outputSmallest.setText(String.valueOf(value)) ;
        
        return smallest;              
    }
    
    private int power ()
    {    
        int power = 0;
        
       // This gets the value from the user    

        number = Integer.parseInt(txtNumber.getText()); 
        power = Integer.parseInt(txtPower.getText()); 

        // This does the math, converts to string and displays the answer

        double result = Math.pow(number, power);
        int value = (int)result;
        outputPower.setText(String.valueOf(value)) ;
        
        return power;              
    }
    
    private int hypotenuse ()
    {    
        int hypotenuse = 0;
        
        // This gets the value from the user    
    
        side1 = Integer.parseInt(txtSide1.getText()); 
        side2 = Integer.parseInt(txtSide2.getText()); 

        // This does the math, converts to string and displays the answer

        double result = Math.hypot(side1,side2);
        int value = (int)result;
        outputHypotenuse.setText(String.valueOf(value)) ;
        
        return hypotenuse;              
    }
    
    private int roundingD ()
    {    
        int roundingD = 0;
        
        // This gets the value from the user    
        
        roundDown = Double.parseDouble(txtDown.getText()); 

        // This does the math, converts to string and displays the answer

        double result = Math.floor(roundDown);
        outputRDown.setText(String.valueOf(result)) ;  
        
        return roundingD;              
    }
    
    private int roundingU ()
    {    
        int roundingU = 0;
        
        // This gets the value from the user    
        
        roundUp = Double.parseDouble(txtUp.getText());   

        // This does the math, converts to string and displays the answer

        double result = Math.ceil(roundUp);
        outputRUp.setText(String.valueOf(result)) ; 
        
        return roundingU;              
    }
    
    private int multiplying ()
    {    
        int multiplying = 0;
        
        // This gets the value from the user    
        
        multiply1 = Integer.parseInt(txtMult1.getText());  
        multiply2 = Integer.parseInt(txtMult2.getText());

        // This does the math, converts to string and displays the answer

        double result = multiply1*multiply2;
        outputMultiply.setText(String.valueOf(result)) ;   
        
        return multiplying;              
    }
    
    private int dividing ()
    {    
        int dividing = 0;
        
        // This gets the value from the user    
        
        divide1 = Integer.parseInt(txtDivide1.getText());  
        divide2 = Integer.parseInt(txtDivide2.getText());  

        // This does the math, converts to string and displays the answer

        double result = divide1/divide2;
        outputDivide.setText(String.valueOf(result)) ;   
        
        return dividing;              
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bhatt_MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bhatt_MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bhatt_MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bhatt_MathMethodsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bhatt_MathMethodsFrame().setVisible(true);
            }
                    
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonDown;
    private javax.swing.JButton buttonHypotenuse;
    private javax.swing.JButton buttonLargest;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonPowers;
    private javax.swing.JButton buttonSmallest;
    private javax.swing.JButton buttonUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDown;
    private javax.swing.JLabel lblHypotenuse;
    private javax.swing.JLabel lblLargest;
    private javax.swing.JLabel lblPowers;
    private javax.swing.JLabel lblRadians;
    private javax.swing.JLabel lblRoot;
    private javax.swing.JLabel lblSmallest;
    private javax.swing.JLabel lblUp;
    private javax.swing.JTextField outputDivide;
    private javax.swing.JTextField outputHypotenuse;
    private javax.swing.JTextField outputLargest;
    private javax.swing.JTextField outputMultiply;
    private javax.swing.JTextField outputPower;
    private javax.swing.JTextField outputRDown;
    private javax.swing.JTextField outputRUp;
    private javax.swing.JTextField outputSmallest;
    private javax.swing.JTextField txtDivide1;
    private javax.swing.JTextField txtDivide2;
    private javax.swing.JTextField txtDown;
    private javax.swing.JTextField txtLarge1;
    private javax.swing.JTextField txtLarge2;
    private javax.swing.JTextField txtMult1;
    private javax.swing.JTextField txtMult2;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPower;
    private javax.swing.JTextField txtSide1;
    private javax.swing.JTextField txtSide2;
    private javax.swing.JTextField txtSmallest1;
    private javax.swing.JTextField txtSmallest2;
    private javax.swing.JTextField txtUp;
    // End of variables declaration//GEN-END:variables
}
